### ISSUE TITLE
Trying to install via chrome store, getting invalid manifest error

### ISSUE THREAD

**Issue by aharpervc** [vikbez/Verbatim-search#2] opened 2016-03-03 15:01 UTC
![image](https://cloud.githubusercontent.com/assets/441085/13498162/ce6c786c-e126-11e5-99f3-f9c12b6a098c.png)

**Comment by vikbez** [comment] 2016-03-03 21:51
After testing on multiple machines, I can't reproduce this error.
What version of chrome are you using ?
Can you try again ?

**Comment by aharpervc** [comment] 2016-03-04 14:20
Chrome is Version 49.0.2623.75 beta-m (64-bit). Still getting that error today as well.

**Comment by martharay** [comment] 2016-03-19 15:10
Google made this extension disappear from my machines last week.  And the store gives me the error above too.  So I found this site, did some reading on how to bypass the store, and tried the "load unpacked extension" feature in chrome and it kept failing when it hit icon 19a.  So I had a hunch that the letter "a" was causing the error. So I text edited the manifest.json to just make it 19.  The load error would then error on 19b.  So I changed that to the number 16.  and then it worked!  I have the wonderful verbatim search back again.

**Comment by vikbez** [comment] 2016-03-19 16:14
Yes, I'm on it, should be fixed tonight, it seems that google changed the manifest requirement/format, so I will look at this :)

**Comment by vikbez** [comment] 2016-03-19 22:36
I just published the version 1.5 that should be fixed !
Usually it shouldn't take more than 1 hour.

**Closed as completed by vikbez** 2016-03-19 22:36 UTC

**Comment by martharay** [comment] 2016-03-21 02:54
It reinstalled on my chrome automatically.  So all is well with the world again.

**Comment by aharpervc** [comment] 2016-03-21 13:50
Seems to be working again :+1:
